name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-website:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: Build
        run: |
          cd ./website
          flutter pub get
          flutter build web
          cd ./scripts
          dart bundler.dart
      - uses: papeloto/action-zip@v1
        with:
          files: micropub/static/
          dest: static.zip
      - uses: actions/upload-artifact@master
        with:
          name: static
          path: static.zip

  build-server-ubuntu:
    needs: build-website
    name: Build server (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1 
      - name: Build
        run: |
          cd ./micropub
          dart pub get
          dart compile exe bin/micropub.dart
      - uses: actions/upload-artifact@master
        with:
          name: micropub-ubuntu
          path: micropub/bin/micropub.exe

  build-server-macos:
    needs: build-website
    name: Build server (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1 
      - name: Build
        run: |
          cd ./micropub
          dart pub get
          dart compile exe bin/micropub.dart
      - uses: actions/upload-artifact@master
        with:
          name: micropub-macos
          path: micropub/bin/micropub.exe

  build-server-windows:
    needs: build-website
    name: Build server (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1 
      - name: Build
        run: |
          cd ./micropub
          dart pub get
          dart compile exe bin/micropub.dart
      - uses: actions/upload-artifact@master
        with:
          name: micropub-windows
          path: micropub/bin/micropub.exe

  publish:
    needs: [build-server-ubuntu,build-server-macos,build-server-windows]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        id: download
        with:
          path: artifacts
      - name: List artifact files
        run: ls -R
      - name: Renamming files
        run: |
            mv ${{steps.download.outputs.download-path}}/micropub-ubuntu/micropub.exe ${{steps.download.outputs.download-path}}/micropub-macos/micropub-macos.exe
            mv ${{steps.download.outputs.download-path}}/micropub-ubuntu/windows.exe ${{steps.download.outputs.download-path}}/micropub-windows/micropub-windows.exe
            mv ${{steps.download.outputs.download-path}}/micropub-ubuntu/ubuntu.exe ${{steps.download.outputs.download-path}}/micropub-ubuntu/micropub-ubuntu.exe
    
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{steps.download.outputs.download-path}}/micropub-macos/micropub-macos.exe
            ${{steps.download.outputs.download-path}}/micropub-windows/micropub-windows.exe
            ${{steps.download.outputs.download-path}}/micropub-ubuntu/micropub-ubuntu.exe
            ${{steps.download.outputs.download-path}}/static/static.zip
  
